---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpuexecutioncap: 90
    cpus: 2

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[collectd::install]
      - recipe[kagent::install]
      - recipe[kagent::default]
      - recipe[collectd::server]
      - recipe[collectd::attr-driven]

    attributes:
         kagent:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         kmon:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         collectd:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "enabled"
